### ISSUE TITLE
Adding a comment on a case fails sometimes

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/trailblazer#287]
As reported by @peterpru for a specific case.

It seems like the comment column in the database supports the utf8 encoding when it likely should support utf8mb4 instead (supports a wider range of characters).

This is the error from the logs
```
...skipping...
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/home/src/app/trailblazer/server/api.py", line 82, in analysis
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     return self.view_functions[rule.endpoint](**req.view_args)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     rv = self.dispatch_request()
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     raise value
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     reraise(exc_type, exc_value, tb)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/flask_cors/extension.py", line 176, in wrapped_function
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     rv = self.handle_user_exception(e)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     response = self.full_dispatch_request()
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: Traceback (most recent call last):
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: [1B blob data]
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: The above exception was the direct cause of the following exception:
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: [1B blob data]
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: pymysql.err.DataError: (1366, "Incorrect string value: '\\xEF\\xBB\\xBFFAI...' for column 'comment' at row 1")
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     raise errorclass(errno, errval)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     err.raise_mysql_exception(self._data)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     packet.raise_for_error()
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 772, in _read_packet
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     first_packet = self.connection._read_packet()
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 1200, in read
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     result.read()
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 822, in _read_query_result
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 558, in query
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     conn.query(q)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 322, in _query
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     result = self._query(query)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/pymysql/cursors.py", line 153, in execute
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     cursor.execute(statement, parameters)
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:     self.dialect.do_execute(
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]:   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: Traceback (most recent call last):
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: [2023-09-26 11:34:53,332] ERROR in app: Exception on /api/v1/analyses/279923 [PUT]
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: [2023-09-26 11:34:53 +0200] [5] [DEBUG] PUT /api/v1/analyses/279923
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: 10.0.2.100 - - [26/Sep/2023:11:34:53 +0200] "OPTIONS /api/v1/analyses/279923 HTTP/1.0" 204 0 "https://cigrid.scilifelab.se/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safa>
Sep 26 11:34:53 cg-prod-services.scilifelab.se podman[2131706]: [2023-09-26 11:34:53 +0200] [4] [DEBUG] OPTIONS /api/v1/analyses/279923
Sep 26 11:34:47 cg-prod-services.scilifelab.se podman[3158884]: [2023-09-26 11:34:47 +0200] [7] [DEBUG] Closing connection.

```

**Comment by henrikstranneheim** [comment]
Functionality seem to be working - reopen if needed.
